# Generated by Django 2.0.6 on 2018-06-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='automodel',
            name='galery_photo',
            field=models.ManyToManyField(related_name='galery_photo', to='shop.Photo'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='main_options',
            field=models.ManyToManyField(to='shop.MainOptions'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='main_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_photo', to='shop.Photo'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Mark'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='options',
            field=models.ManyToManyField(to='shop.Options'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.VideoExample'),
        ),
    ]
