# Generated by Django 2.0.6 on 2018-06-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_orderbuy_ordercall_partnerscall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automodel',
            options={'verbose_name': 'Модель авто', 'verbose_name_plural': 'Модели авто'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Описание товара', 'verbose_name_plural': 'Описания товаров'},
        ),
        migrations.AlterModelOptions(
            name='mainoptions',
            options={'verbose_name': 'Основные параметры', 'verbose_name_plural': 'Основные параметры'},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Марка авто', 'verbose_name_plural': 'Марки авто'},
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='orderbuy',
            options={'verbose_name': 'Оформление покупки', 'verbose_name_plural': 'Оформления покупки'},
        ),
        migrations.AlterModelOptions(
            name='ordercall',
            options={'verbose_name': 'Заказ звонка', 'verbose_name_plural': 'Заказы звонка'},
        ),
        migrations.AlterModelOptions(
            name='partnerscall',
            options={'verbose_name': 'Заказ звонка партнера', 'verbose_name_plural': 'Заказы звонка партнера'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото регистраторов', 'verbose_name_plural': 'Фото регистраторов'},
        ),
        migrations.AlterModelOptions(
            name='videoexample',
            options={'verbose_name': 'Пример видео', 'verbose_name_plural': 'Примеры видео'},
        ),
    ]
