# Generated by Django 2.0.6 on 2018-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180612_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercall',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerscall',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerscall',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
