# Generated by Django 2.0.6 on 2018-06-12 21:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180612_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbuy',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 22, 34, 608697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordercall',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 22, 34, 607120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='partnerscall',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 12, 21, 22, 34, 607873, tzinfo=utc)),
        ),
    ]
