# Generated by Django 2.0.6 on 2018-06-13 03:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180612_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='automodel',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderbuy',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 3, 23, 54, 591581, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordercall',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 3, 23, 54, 589850, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='partnerscall',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 3, 23, 54, 590764, tzinfo=utc)),
        ),
    ]
