# Generated by Django 2.0.6 on 2018-07-02 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180702_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automodel',
            name='options',
        ),
        migrations.AddField(
            model_name='automodel',
            name='options',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Options'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderbuy',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 2, 5, 7, 53, 91150, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordercall',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 2, 5, 7, 53, 89506, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='partnerscall',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 2, 5, 7, 53, 90318, tzinfo=utc)),
        ),
    ]
